version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/app:/var/www/app

  php:
    build: ./docker/php
    ports:
      - 9000:9000
    restart: always
    depends_on:
      - db
    volumes:
      - ./src/app:/var/www/app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: aseki
      MYSQL_PASSWORD: aseki
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 4306:3306
